name: Test
version: ${project.version}
main: fr.deums.aurium.test.Main
api-version: 1.17
authors: [ deums ]
description: Plugin de test
commands:
  home:
    description: Se téléporter à un home
    usage: /<command> home
  sethome:
    description: Poser un home
    usage: /<command>
