name: Test
version: 1.0-SNAPSHOT
main: fr.deums.aurium.test.Main
api-version: 1.17
authors: [ deums ]
description: Plugin de test
commands:
  home:
    description: Se téléporter à un home
    usage: /<command> home
  sethome:
    description: Poser un home
    usage: /<command> home
  delhome:
    description : Supprimer un home
    usage : /<command> home
permissions:
  fr.deums.aurium.test.home.bypass:
    description: allow home bypass timer
    default: op;